### ISSUE TITLE
fix a bug(NullPointerException) when receiving resource

### ISSUE THREAD

**Issue by sergey-leonidovich-shevchenko** [Lancer-Serega/SaperGame#1]
Fix a bug(NullPointerException) when receiving resource
![photo_2018-04-01_06-26-28](https://user-images.githubusercontent.com/16123649/38169557-c38ee448-3575-11e8-953c-c20a46d8a8d5.jpg)

**Comment by Lancer-Serega** [comment]
Resolve

**Comment by sergey-leonidovich-shevchenko** [comment]
Resolve
