### ISSUE TITLE
Add coordinates in game field

### ISSUE THREAD

**Issue by sergey-leonidovich-shevchenko** [Lancer-Serega/SaperGame#3]
![2018-04-02 04-52-07](https://user-images.githubusercontent.com/16123649/38180108-ac8d6c0c-3632-11e8-8ba7-4fa940c954de.png)

**Comment by Lancer-Serega** [comment]
![2018-04-02 04-52-07](https://user-images.githubusercontent.com/16123649/38180100-9ff37202-3632-11e8-9d6b-af7cdfaab94a.png)

**Comment by sergey-leonidovich-shevchenko** [comment]
Complete
