### ISSUE TITLE
Add class Bomb

### ISSUE THREAD

**Issue by sergey-leonidovich-shevchenko** [Lancer-Serega/SaperGame#7]
![2018-04-02 09-13-06](https://user-images.githubusercontent.com/16123649/38185291-26db41f0-3656-11e8-9d87-c02af5d5d61b.png)

**Comment by Lancer-Serega** [comment]
![2018-04-02 09-13-06](https://user-images.githubusercontent.com/16123649/38185278-1f2b2632-3656-11e8-8818-d79fc9b57fff.png)

**Comment by sergey-leonidovich-shevchenko** [comment]
Complete
